
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "XXXXX-docker.pkg.dev/project-name/registry/image-name",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "XXXXX-docker.pkg.dev/project-name/registry/image-name",
      ]
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET